Repository LTUC/BTEC-Fall-Training, pull requests merged in 2022-11, with the labels that each got.

#2 add to text file
  CLass-03/Fadi Alnajar/README.md
  CLass-03/Fadi Alnajar/wierframe.png
Labels: complete

#4 Create Class -04
  Class -04
Labels: complete

#3 Add wireframe
  CLass-03/BasharAysar/READEM.md
  CLass-03/BasharAysar/Screenshot (146).png
Labels: complete

#5 add an image about nasa
  Class-04/abdullah-qdad/download.png
  Class-04/abdullah-qdad/index.html
  Class-04/abdullah-qdad/styles.css
Labels: complete

#7 Add HTML structure
  Class-04/Ahmad Ghanem/README.md
  Class-04/Ahmad Ghanem/index.html
Labels: complete

#8 add to txt
  Class-04/Majd.Alissa/index.html
  Class-04/Majd.Alissa/readme.md
Labels: complete

#17 Add wierfreme for portfolio
  Class-03/Tasneem/README.md
  Class-03/Tasneem/Untitled.png
  Class-03/Tasneem/wearfream1.jpg
  Class-03/Tasneem/wearfream1.jpg:Zone.Identifier
  Class-03/Tasneem/wearfream2.png
  Class-03/Tasneem/wearfream2.png:Zone.Identifier
Labels: complete

#10 New wireframe
  Class-03/Rahaf Bedas/1.PNG
  Class-03/Rahaf Bedas/2.PNG
  Class-03/Rahaf Bedas/README.md
  Class-04/Rahaf-Bedas/index.html
  Class-04/Rahaf-Bedas/index2.html
  Class-04/Rahaf-Bedas/index3.html
  Class-04/Rahaf-Bedas/style.css
  Class-04/Rahaf-Bedas/style2.css
  Class-04/Rahaf-Bedas/style3.css
Labels: complete

#11 Add a review of git and gitHub
  Class-03/Farah Yasin/HW_wireframe.png
  Class-03/Farah Yasin/README.md
  Class-04/Farah Yasin/index.html
Labels: complete

#15 Fadi Al-Najar-Task-02
  Class-04/Fadi Al-Najar/index.html
  Class-04/Fadi Al-Najar/style.css
Labels: complete

#18 add to text file
  Class-03/hazar/README.md
  project/index.html
Labels: complete

#22 First lecturt for JS
  Class-06/Tasneem/Index.html
  Class-06/Tasneem/app.js
  Class-06/Tasneem/style.css
Labels: complete

#24 Wireframe Task
  CLass-03/khalil Al-Mazaideh/Screenshot 2022-11-09 231704.png
  CLass-03/khalil Al-Mazaideh/Screenshot 2022-11-09 231704.png:Zone.Identifier
Labels: complete

#23 The first lecture in JavaScript Js01
  Class-05/Ahmad Ghanem/index.html
  Class-05/Ahmad Ghanem/style.css
  Class-05/README.md
  Class-05/demo/index.html
  Class-05/demo/styles.css
  Class-06/Ahmad Ghanem/app.js
  Class-06/Ahmad Ghanem/index.html
  Class-06/Ahmad Ghanem/style.css
Labels: complete

#16 Add HTML Demo
  Class-05/Ahmad Ghanem/index.html
  Class-05/Ahmad Ghanem/style.css
Labels: complete

#19 html with some css
  Class-05/Hassan Alnobani/Demo/index.html
  Class-05/Hassan Alnobani/Demo/style.css
  Class-05/README.md
  Class-06/Hassan Alnobani/Demo/app.js
  Class-06/Hassan Alnobani/Demo/index.html
  Class-06/Hassan Alnobani/Demo/style.css
Labels: complete, merge-conflict

#20 add html
  CLass-03/BasharAysar/BasharHTML/image/download (1).jpg
  CLass-03/BasharAysar/BasharHTML/image/download.jpg
  CLass-03/BasharAysar/BasharHTML/image/sports-supplements.jpg
  CLass-03/BasharAysar/BasharHTML/index.html
  CLass-03/BasharAysar/BasharHTML/style.css
  Class-04/BasharAlhoushn/HTML/image/download (1).jpg
  Class-04/BasharAlhoushn/HTML/image/download.jpg
  Class-04/BasharAlhoushn/HTML/image/sports-supplements.jpg
  Class-04/BasharAlhoushn/HTML/index.html
  Class-04/BasharAlhoushn/HTML/style.css
  Class-04/BasharAlhoushn/README.MD
Labels: complete, merge-conflict, resolved

#29 Adding Wireframes
  Class-03/Petestein/Int2html/README.md
  Class-03/Petestein/Int2html/Readme2.md
  Class-03/Petestein/Int2html/Style.css
  Class-03/Petestein/Int2html/index.html
  Class-03/Petestein/Readme.md
  Class-03/Petestein/Readme2.md
  Class-03/Petestein/Style.css
  Class-03/Petestein/Try.png
  Class-03/Petestein/index.html
  Class-04/Petestein/Readme2.md
  Class-04/Petestein/Style.css
  Class-04/Petestein/index.html
  Class-04/Petestein/logo RGB.png
  Class-05/Petestein/apps.js
  Class-05/Petestein/index.html
  Class-05/Petestein/style.css
Labels: enhancement, complete
